name: Build ParaView and test paraview-config

on: [push]

env:
  PARAVIEW_SUPERBUILD_DIR: ${{ github.workspace }}/build
  PARAVIEW_VERSION: 5.11.0

jobs:
  build-paraview:
    name: Build ParaView Superbuild
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ParaView
        run: |
          git clone -b v${PARAVIEW_VERSION} --depth 1 --recursive https://gitlab.kitware.com/paraview/paraview-superbuild.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libgl1-mesa-dev \
          libxt-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev \
          ninja-build libosmesa6 libosmesa6-dev 

      - name: Configure
        run: |
          mkdir $PARAVIEW_SUPERBUILD_DIR
          cd $PARAVIEW_SUPERBUILD_DIR
          cmake \
          -GNinja \
          -DPARAVIEW_BUILD_EDITION=CATALYST_RENDERING \
          -DENABLE_osmesa=ON \
          -DUSE_SYSTEM_osmesa=ON \
          -DENABLE_python3=ON \
          -DUSE_SYSTEM_python3=ON \
          -DENABLE_mpi=ON \
          -DUSE_SYSTEM_mpi=ON \
          -Dparaview_SOURCE_SELECTION=${PARAVIEW_VERSION} \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          $GITHUB_WORKSPACE/paraview-superbuild

      - name: Build
        run: ninja
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}

      - name: Package
        run: tar -czvf paraview-v${PARAVIEW_VERSION}.tar.gz -C $PARAVIEW_SUPERBUILD_DIR/install .

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: paraview-v${{ env.PARAVIEW_VERSION }}
          path: paraview-v${{ env.PARAVIEW_VERSION }}.tar.gz
          if-no-files-found: error

      - name: Test paraview-config with default CMake version
        continue-on-error: true
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin

      - name: Install older CMake version
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh
          chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh
          sudo ./cmake-${CMAKE_VERSION}-linux-x86_64.sh --prefix=/usr/local --exclude-subdir
          cmake --version
        env:
          CMAKE_VERSION: 3.22.6

      - name: Test paraview-config with older CMake version
        continue-on-error: true
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin


  test-paraview-config:
    name: Test paraview-config
    needs: build-paraview
    runs-on: ubuntu-20.04

    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: paraview-v${{ env.PARAVIEW_VERSION }}

      - name: Untar
        run: |
          mkdir -p $PARAVIEW_SUPERBUILD_DIR/install
          cd $PARAVIEW_SUPERBUILD_DIR/install
          tar -xzvf $GITHUB_WORKSPACE/paraview-v${PARAVIEW_VERSION}.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libgl1-mesa-dev \
          libxt-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev \
          ninja-build libosmesa6 libosmesa6-dev llvm-12-dev
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 12

      - name: Test paraview-config with default CMake version
        continue-on-error: true
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin

      - name: Install older CMake version
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh
          chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh
          sudo ./cmake-${CMAKE_VERSION}-linux-x86_64.sh --prefix=/usr/local --exclude-subdir
          cmake --version
        env:
          CMAKE_VERSION: 3.22.6

      - name: Test paraview-config with older CMake version
        continue-on-error: true
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin

